name: tests
run-name: run tests and create code coverage
on: [push]
jobs:
  test-php83:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: xdebug
          coverage: xdebug

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: PHPUnit Tests
        env:
          XDEBUG_MODE: coverage
        run: vendor/bin/phpunit --bootstrap vendor/autoload.php --configuration phpunit.xml tests --coverage-clover ./coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
